<?php

namespace Uek\MovieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
	
	public function findOneByName($gname)
	{
		$qb = $this->createQueryBuilder('g')
		->where('g.name = :gname')
		->setMaxResults(1)
		->setParameters(array('gname' => $gname));
		
		$genres = $qb->getQuery()->getResult();
		if (count($genres))
		{
			return $genres[0];
		}
		else 
		{
			return null;
		}
	}
}
