<?php

namespace Uek\MovieBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Uek\MovieBundle\Entity;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
	public function findByGenre(Genre $genre)
	{
		return $genre->getMovies();
	}
}
