movies:
    prefix: /movies
    resource: "@UekMovieBundle/Controller/MovieController.php"
    type:     annotation
 
genres:
    prefix: /genres
    resource: "@UekMovieBundle/Controller/GenreController.php"
    type:     annotation
 