services:
    uek.moviebundle.genre.helper:
        class: Uek\MovieBundle\Helpers\GenreHelper
        arguments: ['@doctrine.orm.entity_manager']        
    uek.moviebundle.movie.helper:
        class: Uek\MovieBundle\Helpers\MovieHelper
        arguments: ['@doctrine.orm.entity_manager', '@uek.moviebundle.genre.helper']        
#    uek_movie.example:
#        class: Uek\MovieBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

