uek_store:
    resource: "@UekStoreBundle/Resources/config/routing.yml"

uek_movie:
    resource: "@UekMovieBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

demo:
    resource: "@AppBundle/Controller/DemoController.php"
    type:     annotation

