uek_store:
    resource: "@UekStoreBundle/Resources/config/routing.yml"
    prefix:   /

uek_movie:
    resource: "@UekMovieBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation

demo:
    prefix: /demo
    resource: "@AppBundle/Controller/DemoController.php"
    type:     annotation
