<?php

namespace Uek\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	// Something stragne, the fosUserBundle's User fyndByUsernae does not work.
	// This is a workaround
	public function findOneByUsername($username)
	{		
		$users = $this->getEntityManager()->getRepository('UekUserBundle:User')->findAll();
		
		foreach ($users as $user)
		
		if ($user->getUsername() == $username)
		{
			return $user;
		}

		return null;			
	}
}
